backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "news"
    label: "Newws"
    folder: "src/pages/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "news-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
  - name: "work"
    label: "Work"
    folder: "src/pages/work"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "work",
        }
      - { label: Company, name: company, widget: string }
      - { label: Title, name: title, widget: string }
      - {
          label: Details,
          name: details,
          widget: object,
          fields:
            [
              {
                label: Clients,
                name: clients,
                widget: list,
                fields: [{ label: Name, name: name, widget: string }],
              },
              { label: Deliverables, name: deliverables, widget: string },
              {
                label: Downloads,
                name: downloads,
                widget: list,
                fields:
                  [
                    { label: Name, name: name, widget: string },
                    {
                      label: Link,
                      name: link,
                      widget: string,
                      required: false,
                    },
                  ],
              },
              {
                label: Credits,
                name: credits,
                widget: list,
                fields:
                  [
                    { label: Name, name: name, widget: string },
                    {
                      label: Link,
                      name: link,
                      widget: string,
                      required: false,
                    },
                  ],
              },
            ],
        }
      - { label: "Main Image", name: "mainImage", widget: "image" }
      - { label: Preview, name: preview, widget: string }
      - { label: Story, name: story, widget: text }
      - {
          label: Gallery Block,
          name: gallery_block,
          widget: list,
          fields:
            [
              {
                label: "Layout Type",
                name: "layout_type",
                widget: "select",
                options:
                  [
                    "equal",
                    "fullscreen",
                    "left double size",
                    "right double size",
                  ],
              },
              {
                label: Gallery Items,
                name: gallery_items,
                widget: list,
                fields:
                  [
                    { label: "Image", name: "image", widget: "image" },
                    {
                      label: "Vimeo id",
                      name: "vimeo",
                      widget: "string",
                      required: false,
                    },
                  ],
              },
            ],
        }
